version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin https://924452605616.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPO=$(aws ecr describe-repositories --region ap-northeast-1 --repository-names example --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - docker build - t $IMAGE .
      - docker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"example","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
